changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - github-actions
      - dependabot
  categories:
    - title: Breaking Changes
      labels:
        - breaking-change
        - breaking
    - title: Features
      labels:
        - feature
        - enhancement
    - title: Fixes
      labels:
        - bug
        - fix
    - title: Documentation
      labels:
        - documentation
        - docs
    - title: Build, CI, and Maintenance
      labels:
        - build
        - ci
        - chore
        - dependencies
        - refactor
    - title: Other Changes
      labels:
        - "*"
